<?php

return [

    'categories' => [
        'general' => 'General',
        'tax_compliance' => 'Tax & compliance',
        'trade' => 'International trade',
        'billing' => 'Billing cycles',
        'adjustments' => 'Adjustments',
        'collections' => 'Collections',
        'specialized' => 'Specialized',
    ],

    'types' => [
        'standard' => [
            'label' => 'Standard Invoice',
            'description' => 'Regular bill issued for products or services.',
            'category' => 'general',
            'layout' => 'stripe',
            'title' => 'INVOICE',
            'number_label' => 'Invoice #',
        ],
        'pro_forma' => [
            'label' => 'Pro Forma Invoice',
            'description' => 'Preliminary invoice sent before delivery or payment.',
            'category' => 'general',
            'layout' => 'stripe',
            'title' => 'PRO FORMA INVOICE',
            'number_label' => 'Pro forma #',
            'header_note' => 'This is not a tax invoice until confirmed.',
        ],
        'commercial' => [
            'label' => 'Commercial Invoice',
            'description' => 'Used in international trade and customs.',
            'category' => 'trade',
            'layout' => 'classic',
            'title' => 'COMMERCIAL INVOICE',
            'number_label' => 'Commercial invoice #',
        ],
        'tax' => [
            'label' => 'Tax Invoice',
            'description' => 'Includes GST, VAT, or other tax details.',
            'category' => 'tax_compliance',
            'layout' => 'classic',
            'title' => 'TAX INVOICE',
            'number_label' => 'Tax invoice #',
            'tax_type' => 'vat',
        ],
        'sales' => [
            'label' => 'Sales Invoice',
            'description' => 'Issued after a sale is completed.',
            'category' => 'general',
            'layout' => 'stripe',
            'title' => 'SALES INVOICE',
            'number_label' => 'Sales invoice #',
        ],
        'purchase' => [
            'label' => 'Purchase Invoice',
            'description' => 'Received by the buyer from a supplier.',
            'category' => 'general',
            'layout' => 'classic',
            'title' => 'PURCHASE INVOICE',
            'number_label' => 'Purchase #',
        ],
        'recurring' => [
            'label' => 'Recurring Invoice',
            'description' => 'Generated repeatedly for subscriptions or services.',
            'category' => 'billing',
            'layout' => 'stripe',
            'title' => 'RECURRING INVOICE',
            'number_label' => 'Billing period #',
        ],
        'credit_memo' => [
            'label' => 'Credit Invoice (Credit Memo)',
            'description' => 'Reduces amount due or records a refund adjustment.',
            'category' => 'adjustments',
            'layout' => 'stripe',
            'title' => 'CREDIT MEMO',
            'number_label' => 'Credit note #',
            'accent' => '#059669',
        ],
        'debit_memo' => [
            'label' => 'Debit Invoice (Debit Memo)',
            'description' => 'Additional amount charged to the customer.',
            'category' => 'adjustments',
            'layout' => 'stripe',
            'title' => 'DEBIT MEMO',
            'number_label' => 'Debit note #',
            'accent' => '#dc2626',
        ],
        'interim' => [
            'label' => 'Interim Invoice',
            'description' => 'Partial billing for project milestones.',
            'category' => 'billing',
            'layout' => 'stripe',
            'title' => 'INTERIM INVOICE',
            'number_label' => 'Interim #',
        ],
        'final' => [
            'label' => 'Final Invoice',
            'description' => 'Last invoice after project completion.',
            'category' => 'billing',
            'layout' => 'classic',
            'title' => 'FINAL INVOICE',
            'number_label' => 'Final invoice #',
        ],
        'past_due' => [
            'label' => 'Past Due Invoice',
            'description' => 'Reminder for overdue payment.',
            'category' => 'collections',
            'layout' => 'stripe',
            'title' => 'PAST DUE INVOICE',
            'number_label' => 'Invoice #',
            'accent' => '#dc2626',
            'header_note' => 'Payment is overdue. Please remit immediately.',
        ],
        'timesheet' => [
            'label' => 'Timesheet Invoice',
            'description' => 'Based on hours worked.',
            'category' => 'specialized',
            'layout' => 'stripe',
            'title' => 'TIMESHEET INVOICE',
            'number_label' => 'Timesheet #',
        ],
        'retainer' => [
            'label' => 'Retainer Invoice',
            'description' => 'Advance payment before work starts.',
            'category' => 'billing',
            'layout' => 'stripe',
            'title' => 'RETAINER INVOICE',
            'number_label' => 'Retainer #',
        ],
        'self_billing' => [
            'label' => 'Self-Billing Invoice',
            'description' => 'Buyer creates invoice on behalf of supplier.',
            'category' => 'tax_compliance',
            'layout' => 'classic',
            'title' => 'SELF-BILLING INVOICE',
            'number_label' => 'Self-billing #',
        ],
        'e_invoice' => [
            'label' => 'E-Invoice',
            'description' => 'Electronically generated invoice.',
            'category' => 'general',
            'layout' => 'stripe',
            'title' => 'E-INVOICE',
            'number_label' => 'E-invoice #',
        ],
        'expense' => [
            'label' => 'Expense Invoice',
            'description' => 'Includes reimbursable expenses.',
            'category' => 'specialized',
            'layout' => 'stripe',
            'title' => 'EXPENSE INVOICE',
            'number_label' => 'Expense report #',
        ],
        'mixed' => [
            'label' => 'Mixed Invoice',
            'description' => 'Contains taxable and non-taxable items.',
            'category' => 'tax_compliance',
            'layout' => 'classic',
            'title' => 'MIXED TAX INVOICE',
            'number_label' => 'Invoice #',
        ],
        'consignment' => [
            'label' => 'Consignment Invoice',
            'description' => 'Used for consignment goods.',
            'category' => 'trade',
            'layout' => 'classic',
            'title' => 'CONSIGNMENT INVOICE',
            'number_label' => 'Consignment #',
        ],
        'export' => [
            'label' => 'Export Invoice',
            'description' => 'For goods exported internationally.',
            'category' => 'trade',
            'layout' => 'classic',
            'title' => 'EXPORT INVOICE',
            'number_label' => 'Export invoice #',
        ],
        'import' => [
            'label' => 'Import Invoice',
            'description' => 'For imported goods.',
            'category' => 'trade',
            'layout' => 'classic',
            'title' => 'IMPORT INVOICE',
            'number_label' => 'Import invoice #',
        ],
        'freelance' => [
            'label' => 'Freelance Invoice',
            'description' => 'Used by freelancers and consultants.',
            'category' => 'specialized',
            'layout' => 'stripe',
            'title' => 'FREELANCE INVOICE',
            'number_label' => 'Invoice #',
        ],
        'service' => [
            'label' => 'Service Invoice',
            'description' => 'For service-based businesses.',
            'category' => 'specialized',
            'layout' => 'stripe',
            'title' => 'SERVICE INVOICE',
            'number_label' => 'Service #',
        ],
        'rental' => [
            'label' => 'Rental Invoice',
            'description' => 'For rent or lease payments.',
            'category' => 'specialized',
            'layout' => 'stripe',
            'title' => 'RENTAL INVOICE',
            'number_label' => 'Rental #',
        ],
        'progress' => [
            'label' => 'Progress Invoice',
            'description' => 'Billing according to work progress.',
            'category' => 'billing',
            'layout' => 'stripe',
            'title' => 'PROGRESS INVOICE',
            'number_label' => 'Progress #',
        ],
        'digital' => [
            'label' => 'Digital Invoice',
            'description' => 'Shared via email or software in digital format.',
            'category' => 'general',
            'layout' => 'stripe',
            'title' => 'DIGITAL INVOICE',
            'number_label' => 'Invoice #',
        ],
        'gst' => [
            'label' => 'GST Invoice (India)',
            'description' => 'GST-compliant invoice with HSN/SAC codes.',
            'category' => 'tax_compliance',
            'layout' => 'classic',
            'title' => 'GST INVOICE',
            'number_label' => 'GST invoice #',
            'tax_type' => 'gst',
            'tax_label' => 'GST',
            'header_note' => 'Include HSN/SAC codes on line items where applicable.',
        ],
        'bill_of_supply' => [
            'label' => 'Bill of Supply (India GST)',
            'description' => 'For composition dealers or non-taxable goods.',
            'category' => 'tax_compliance',
            'layout' => 'classic',
            'title' => 'BILL OF SUPPLY',
            'number_label' => 'Bill of supply #',
            'tax_type' => 'none',
        ],
        'revised' => [
            'label' => 'Revised Invoice',
            'description' => 'Corrected invoice replacing a previous one.',
            'category' => 'adjustments',
            'layout' => 'classic',
            'title' => 'REVISED INVOICE',
            'number_label' => 'Revised #',
            'header_note' => 'This invoice supersedes the previous version.',
        ],
        'receipt' => [
            'label' => 'Receipt Invoice',
            'description' => 'Confirms payment received.',
            'category' => 'general',
            'layout' => 'stripe',
            'title' => 'RECEIPT',
            'number_label' => 'Receipt #',
            'header_note' => 'Payment received — thank you.',
        ],
    ],

];
